# Generated by Django 5.0 on 2023-12-28 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_task_modelo_vt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='imagenes_task',
            new_name='imagenes',
        ),
    ]
